import { Address } from "../classes/Address";
export declare const addresses: {
    BEANSTALK: Address;
    BEANSTALK_PRICE: Address;
    BEANSTALK_FERTILIZER: Address;
    BARNRAISE_CUSTODIAN: Address;
    PIPELINE: Address;
    BEANFT_GENESIS: Address;
    BEANFT_WINTER_ADDRESSES: Address;
    BEAN: Address;
    ROOT: Address;
    UNRIPE_BEAN: Address;
    UNRIPE_BEAN_CRV3: Address;
    WETH: Address;
    DAI: Address;
    USDC: Address;
    USDT: Address;
    CRV3: Address;
    LUSD: Address;
    BEAN_CRV3: Address;
    POOL3: Address;
    TRICRYPTO2: Address;
    POOL_REGISTRY: Address;
    META_FACTORY: Address;
    CRYPTO_FACTORY: Address;
    CURVE_ZAP: Address;
    BEAN_ETH_UNIV2_LP: Address;
    BEAN_LUSD_LP: Address;
};
